---
title: "Untitled"
author: "Enzo Moraes Mescall"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(deSolve)
library(tidyverse)
library(plotly)
```

```{r}
theme_Publication <- function(base_size=14, base_family="helvetica") {
      library(grid)
      library(ggthemes)
      (theme_foundation(base_size=base_size, base_family=base_family)
       + theme(plot.title = element_text(face = "bold",
                                         size = rel(1.2), hjust = 0.5),
               text = element_text(),
               panel.background = element_rect(colour = NA),
               plot.background = element_rect(colour = NA),
               panel.border = element_rect(colour = NA),
               axis.title = element_text(face = "bold",size = rel(1)),
               axis.title.y = element_text(angle=90,vjust =2),
               axis.title.x = element_text(vjust = -0.2),
               axis.text = element_text(), 
               axis.line = element_line(colour="black"),
               axis.ticks = element_line(),
               panel.grid.major = element_line(colour="#f0f0f0"),
               panel.grid.minor = element_blank(),
               legend.key = element_rect(colour = NA),
               legend.position = "bottom",
               legend.direction = "horizontal",
               legend.key.size= unit(0.2, "cm"),
               legend.margin = unit(0, "cm"),
               legend.title = element_text(face="italic"),
               plot.margin=unit(c(10,5,5,5),"mm"),
               strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
               strip.text = element_text(face="bold")
          ))
      
}

scale_fill_Publication <- function(...){
      library(scales)
      discrete_scale("fill","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}

scale_colour_Publication <- function(...){
      library(scales)
      discrete_scale("colour","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}
```


```{r}
predator.pray.model = function(t, State, Pars) {
  with(as.list(c(State, Pars)), {
    dPrey = (b * (1 - Prey/(k - eta * Degradation)) - h_0 * Predator - alpha * Poaching) * Prey + m_0 - m * Degradation
    
    dPredator = ( h_1 * (Prey) - d - beta * RetaliatoryKilling - S * Tourism) * Predator
    
    dTourism = A/Tourism - delta * Degradation
    
    dPoaching = gamma * (r_p * Prey - (Omega + sigma_p * (lambda_0 + lambda * Tourism))) * Poaching

    dRetaliatoryKilling = c * Predator - B * Tourism
    
    dDegradation = G - E_r - I_0 + (P_t - I_t) * Tourism 
  
    equations = c(dPrey, dPredator, dTourism,
                dPoaching, dRetaliatoryKilling, dDegradation)
    
    return(list(0.4*equations))
  })
}

# Parameters and initial condition
Pars = c(gamma = 1,     # speed of poaching adjustment
         r_p =  0.05,   # revenue per poach
         Omega =  0.6,  # opportunity cost
         sigma_p = 0.01,# risk of poaching
         lambda_0 = 5, # base law enforcement level
         lambda = 35,   # law enforcement per investment
         c = 0.375,     # culling rate per predator
         B = 0.5,       # boma construction per unit invested
         E_r = 0.5,     # baseline recovery rate
         I_0 = 0.5,     # baseline government investment
         P_t = 0.3,     # average pollution per tourist
         I_t = 0.1,     # investment into ecology per tourism income
         G = 0.4,       # impact of global warming on degradation
         b = 0.3,       # birth rate of prey
         k = 120,       # carrying capacity of prey
         eta = 1,       # sensitivity of degradation on carrying cap
         h_0 = 0.05,    # effect of hunting on prey population
         alpha = 0.01,  # poaching effectiveness
         m_0 = 1.5,     # baseline migration inwards
         m = 0.5,       # effect of degradation on outwards migration
         h_1 = 0.05,    # conversion of prey biomass into predator biomass
         d = 0.17,      # death rate of predators
         beta = 0.1,    # effectiveness of retaliatory killings
         S = 0.01,      # sensitivity of predators to tourist distractions
       delta = 0.01,  # effect of degradation on tourism
         A = 0.01)      # tourism destination attractiveness saturation

X_0 = c(Prey = 34,
        Predator = 4,
        Tourism = 3,
        Poaching = 1.3,
        RetaliatoryKilling = 15,
        Degradation = 3)
```

```{r}
# Calculating where the equilibrium is gonna be

with(as.list(Pars), {
  Tourism = (E_r + I_0 - G)/(P_t - I_t)
  
  Predator = Tourism * B/c
  
  Degradation = A/(delta*Tourism)
  
  Prey = (Omega + sigma_p * (lambda_0 + lambda * Tourism))/r_p
  
  RetaliatoryKilling =  (h_1 * Prey - d - S * Tourism)/beta
  
  Poaching = ((b * (1 - Prey / (k - eta * Degradation)) - h_0 * Predator) * Prey + m_0 - m * Degradation)/(alpha * Prey)
  
c(Prey = Prey, Pred = Predator, T = Tourism, Poach = Poaching, RK = RetaliatoryKilling, D = Degradation)
})
```

```{r}
# timestep
t = seq(0, 800, 1)

ode(
  func = predator.pray.model,
  y = X_0,
  times = t,
  parms = Pars
) %>% as.data.frame() -> out
```

```{r}
out %>%
gather(variable, value, -time) %>%
ggplot(aes(x = time, y = value, color = variable)) +
geom_line(size = 1) +
  labs(x = 'Time (days)',y = 'Variable values') +
  scale_colour_Publication() +
  theme_Publication()
```


```{r}
t = seq(0, 1200, 0.1)

# Variables the government can change
A_vals = c(0.015, 0.01, 0.005)
I_0_vals = c(0.6,0.5,0.4,0.3)
P_t_vals = c(0.4, 0.3, 0.35)
I_t_vals = c(0.08,0.1,0.12)
lambda_0_vals = c(1,15,39)
lambda_vals = c(39,15,1)
B_vals = c(0.75,0.5,0.25)
Omega_vals = c(1)
```


```{r}
expand.grid(lambda = lambda_vals,
            lambda_0 = lambda_0_vals) %>%
  group_by(lambda, lambda_0) %>%
  do({ode(func = predator.pray.model,
          y = X_0,
          times = t,
          parms = c(lambda_0 = .$lambda_0,
                    lambda = .$lambda,
                    Pars)) %>%
        as.data.frame()}) %>%
  gather(variable, value, -time, -lambda, -lambda_0, -Degradation, - Predator, -RetaliatoryKilling, -Tourism) %>%
  ggplot(aes(x = time, y = value, color = variable)) +
      geom_line() +
      facet_grid(lambda ~ lambda_0, scales='free_y', labeller=label_both) +
      labs(x = 'Time',y = 'Variable values') +
      scale_colour_Publication() +
      theme_Publication()
```

```{r}
# P_t x I_t
expand.grid(P_t = P_t_vals,
            I_t = I_t_vals) %>%
  group_by(P_t, I_t) %>%
  do({ode(func = predator.pray.model,
          y = X_0,
          times = t,
          parms = c(P_t = .$P_t,
                    I_t = .$I_t,
                    Pars)) %>%
        as.data.frame()}) %>%
  gather(variable, value, -time, -I_t, -P_t, -Prey, -Predator, -Poaching, -RetaliatoryKilling, -Degradation) %>% # -Prey, -Predator, -Degradation, - Predator, -RetaliatoryKilling, -Tourism
  ggplot(aes(x = time, y = value, color = variable)) +
      geom_line() +
      facet_grid(I_t ~ P_t, scales='free_y', labeller=label_both) +
      labs(x = 'Time',y = 'Variable values') +
      scale_colour_Publication() +
      theme_Publication()
```

```{r}
# I_0 x I_t
expand.grid(I_0 = I_0_vals,
            I_t = I_t_vals) %>%
  group_by(I_0, I_t) %>%
  do({ode(func = predator.pray.model,
          y = X_0,
          times = t,
          parms = c(I_0 = .$I_0,
                    I_t = .$I_t,
                    Pars)) %>%
        as.data.frame()}) %>%
  gather(variable, value, -time, -I_t, -I_0, -Prey, -Predator, -Poaching, -RetaliatoryKilling, -Degradation) %>% # -Prey, -Predator, -Degradation, - Predator, -RetaliatoryKilling, -Tourism
  ggplot(aes(x = time, y = value, color = variable)) +
      geom_line() +
      facet_grid(I_t ~ I_0, scales='free_y', labeller=label_both) +
      labs(x = 'Time',y = 'Variable values') +
      scale_colour_Publication() +
      theme_Publication()
```

```{r}
# A x B
expand.grid(A = A_vals,
            B = B_vals) %>%
  group_by(A, B) %>%
  do({ode(func = predator.pray.model,
          y = X_0,
          times = t,
          parms = c(A = .$A,
                    B = .$B,
                    Pars)) %>%
        as.data.frame()}) %>%
  gather(variable, value, -time, -A, -B, -Prey, -Poaching, -Degradation) %>% # -Prey, -Predator, -Degradation, - Predator, -RetaliatoryKilling, -Tourism
  ggplot(aes(x = time, y = value, color = variable)) +
      geom_line() +
      facet_grid(A ~ B, scales='free_y', labeller=label_both) +
      labs(x = 'Time',y = 'Variable values') +
      scale_colour_Publication() +
      theme_Publication()
```

```{r}
out %>%
  ggplot(aes(x = Predator,y = Prey, colour = time)) +
  geom_path() +
  geom_point(aes(x = X_0[2], y = X_0[1]), colour="red") +
  labs(title = "Predator x Pray Dynamics in the System of ODEs",
       subtitle = "Red point indicates initial condition",
       x = "Predator Population (Thousands)",
y = "Prey Population (Thousands)") +
  theme_Publication() +
  theme(legend.key.size= unit(0.8, "cm"))
```

```{r}
out %>%
plot_ly(x = ~Predator, y = ~Prey, z = ~Poaching, color = ~time) %>%
    add_paths()
```






