---
title: "Untitled"
author: "Enzo Moraes Mescall"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(deSolve)
library(phaseR)
library(tidyverse)
```

```{r}
predator.pray.model = function(t, State, Pars) {
  with(as.list(c(State, Pars)), {
    dPredator = a*x - b*x*y
    dPrey     = d*b*x*y -c*y
    
    equations = c(dPredator, dPrey)
    return(list(equations))
  })
}

# Time vectors, parameters, and initial condition
t = seq(0, 60, 0.1)

Pars = c(a = 1.0,
         b = 0.1,
         c = 1.5,
         d = 0.75)

X_0 = c(x = 4, y = 2)
```

```{r}
ode(
  func = predator.pray.model,
  y = X_0,
  times = t,
  parms = Pars
) %>% as.data.frame() -> out
```

```{r}
out %>%
  gather(variable, value, -time) %>%
  ggplot(aes(x = time, y = value, color = variable)) +
    geom_line() +
    theme_classic() +
    labs(x = 'time (yr)',y = 'populations')
```

```{r}
a_vals = c(0.3, 0.7, 1)
b_vals = c(0.05, 0.1, 0.3)

expand.grid(a = a_vals, b = b_vals) %>%
  group_by(a, b) %>%
  do({ode(func = predator.pray.model,
          y = X_0,
          times = t,
          parms = c(a=.$a, b=.$b, c = 0.4, d = 2)) %>%
        as.data.frame()}) %>%
  ggplot(aes(x = time)) +
    geom_line(aes(y = x), color = "red") +
    geom_line(aes(y = y), color = "blue") +
    facet_grid(a ~ b, scales='free_y', labeller=label_both) +
    labs(y = "Population")
```

```{r}
flowField = flowField(predator.pray.model,
                      xlim = c(0, 60),
                      ylim = c(0, 30),
                      parameters = Pars,
                      add = FALSE)

trajectory1 = trajectory(predator.pray.model,
                      y0 = c(10, 5),
                      tlim = c(0, 30),
                      parameters = Pars,
                      col = "purple")

trajectory2 = trajectory(predator.pray.model,
                      y0 = c(12, 5),
                      tlim = c(0, 30),
                      parameters = Pars,
                      col = "blue")

trajectory3 = trajectory(predator.pray.model,
                      y0 = c(6, 5),
                      tlim = c(0, 30),
                      parameters = Pars,
                      col = "red")

trajectory3 = trajectory(predator.pray.model,
                y0 = c(1, 25),
                      tlim = c(0, 30),
                      parameters = Pars)
```





 